apiVersion: v1
kind: Secret
metadata:
  name: lastmile-secret
  namespace: lastmile
type: Opaque
stringData:
  JWT_SECRET: "supersecretkey"
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "secret"